# ---- Build stage
FROM gradle:8.7-jdk17 AS build
WORKDIR /src
COPY . .
RUN ./gradlew clean bootJar --no-daemon

# ---- Run stage
FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /src/build/libs/*.jar app.jar

# 12-factor: config por envs
ENV JAVA_OPTS=""
EXPOSE 8080
ENTRYPOINT ["sh","-c","java $JAVA_OPTS -jar app.jar"]
